
[project]
name = "vocex"
version = "0.1.0"
description = ""
authors = [
    {name = "Christoph Minixhofer", email = "christoph.minixhofer@gmail.com"},
]
dependencies = [
    "tqdm>=4.65.0",
    "numpy>=1.24.3",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}